name: Update Dockerfiles
on:
  repository_dispatch:
    types: [update_dockerfiles]
  push:
    paths:
      - 'images/**'
      - 'ubuntu/**'


jobs:
  docker:
    name: Building ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - name: Ubuntu 32bit Dockerfile
            file: ./ubuntu/i386.Dockerfile
            tag: ubuntu32
          # - name: Web Dockerfile
          #   file: ./images/web.Dockerfile
          #   tag: web
          # - name: Android Dockerfile
          #   file: ./images/android.Dockerfile
          #   tag: android
          # - name: Windows Dockerfile
          #   file: ./images/windows.Dockerfile
          #   tag: windows
    env:
      APP_NAME_BASE: "blazium"  # Define a global base app name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME_BASE }}-${{ matrix.tag }}:latest
