name: Multi-Stage Deployment
on:
  repository_dispatch:
    types: [test_deploy]

concurrency:
  group: ci-test_deploy-runner
  cancel-in-progress: true

jobs:
#  mono-glue:
#    name: Building Mono Glue for Mono Editor Builds
#    uses: ./.github/workflows/monoglue.yaml
  linux32:
    name: Building Linux 32bit Editors
    uses: ./.github/workflows/linux32-build.yaml
    with:
      MONO: 0
